### ISSUE TITLE
How to create group?

### ISSUE THREAD

**Issue by chapira** [dyvoid/hue-air#1]
I can't find in conector actions lists - Create group... just Create User..

**Comment by chapira** [comment]
It seems that really doesn't have yet...
http://stackoverflow.com/questions/25513992/philips-hue-how-to-create-group-for-user

**Comment by dyvoid** [comment]
The create group call wasn't part of the original API documentation, so that's why it's not there. I haven't really maintained this library since 1.0, so I've added a notice to the readme to point this out.
Anyways, since you specifically asked I've added a createGroup method to the connector. Hope that helps you out.

**Comment by chapira** [comment]
yes I did it tnx:
heres my code
con.doRequest("/groups",{"lights": ["1","2"],"name": "hueApp"},"POST",retornoCriaGrupo,erroCriaGrupo)
